services:
  - type: web
    name: study-planner-api
    env: python
    buildCommand: "cd frontend && npm install && npx react-scripts build && cd ../backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://*.netlify.app,https://*.render.com 